"""Initial migration

Revision ID: 7a464fcc4926
Revises: 
Create Date: 2026-04-24 09:36:30.210134

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '7a464fcc4926'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=256), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('iris_scans',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('symptom_focus', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('patient_query', sa.Text(), nullable=True),
    sa.Column('detected_condition', sa.String(length=200), nullable=True),
    sa.Column('probability_index', sa.Float(), nullable=True),
    sa.Column('urgency_level', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='urgency_level'), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('vision_profiles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('full_name', sa.String(length=150), nullable=False),
    sa.Column('biological_sex', sa.String(length=16), nullable=True),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('blood_group', sa.String(length=8), nullable=True),
    sa.Column('clinical_history', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vision_profiles')
    op.drop_table('iris_scans')
    op.drop_table('users')
    # ### end Alembic commands ###
